name: Java CI with Maven and SonarCloud

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # 3️⃣ Cacher le repository Maven
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Cacher le cache Sonar
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      # 5️⃣ Build Maven + tests
      - name: Build and test with Maven
        run: mvn clean verify

      # 6️⃣ Analyse SonarCloud
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=CERI-M1-DevOps_tpintegrationcontinue-kebdanisouhila218-beep \
            -Dsonar.organization=CERI-M1-DevOps \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=${{ github.head_ref || github.ref_name }}
